name: Schedule Test
on:
  schedule:
    - cron: '*/10 * * * *' # Runs every 10 minutes
  workflow_dispatch: 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Scheduled run test at $(date)"